### ISSUE TITLE
Add in-app notifications

### ISSUE THREAD

**Issue by spcbfr** [spcbfr/BloodyTwitter#2]
## Description

The goal of this feature is for a given user to receive a notification when someone likes their tweet.

## Implementation steps
- [ ] Add the frontend for a notification icon in the navigation bar
- [ ] Create a new notification
- [ ] Create an event that fires when someone likes a given tweet
- [ ] Link the event and the notification together

## Further Reading
- Thankfully Laravel ships with it's own notification system built-in. it has support for email, sms, markdown notifications and more. the one we're interested in is [Database Notifications](https://laravel.com/docs/10.x/notifications#database-notifications). read through that documentation page if you haven't already.
